apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld-controller
  labels:
    app: hello_world
spec:
  replicas: 10
  selector:
    matchLabels: 
      app: hello_world
  template:
    metadata:
      labels:
        app: hello_world
    containers:
      - name: k8s-demo
        image: arjunachari12/k8s-demo
        ports:
        - name: nodejs-port
          containerPort: 3000
  
